[package]
name = "web_scrapper"
version = "0.1.0"
authors = ["Muhammad Anjum Kaiser <anjumbutt@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.8"
select = "0.4.2"
scraper = "0.9.1"
prettytable-rs = "0.8.0"
